version: '3.7'

services:
  backend:
    build: ./backend
    container_name: monsoon_backend
    command: >
      sh -c "python manage.py migrate &&
             gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:15.1-bullseye
    container_name: monsoon_db
    restart: always
    env_file: .env
    volumes:
      - .dbdata:/var/lib/postgresql/data
    ports:
      - "55432:5432"
  frontend:
    build: ./frontend
    container_name: monsoon_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true