# Generated by Django 4.1.5 on 2023-01-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_tags_posttag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tags",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
