# Generated by Django 4.1.5 on 2023-01-24 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_tags_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posttag",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tag_set",
                related_query_name="tag_set",
                to="posts.post",
            ),
        ),
        migrations.AlterField(
            model_name="posttag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_set",
                related_query_name="post_set",
                to="posts.tags",
            ),
        ),
    ]
